version: '2'
services:
    aplicativo-app:
        image: aplicativo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://aplicativo-postgresql:5432/aplicativo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aplicativo-postgresql:
        extends:
            file: postgresql.yml
            service: aplicativo-postgresql
