/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jhipster;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author mfernandes
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jhipster/hipster.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("JHipster");

        jLabel3.setText("criar nova aplicação");

        jTextField1.setText("nome");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("logo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("criar!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setText("/home/mfernandes/Documentos/nome/");

        jButton3.setText("entidades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("sair automatico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jTextField1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel2))
                                .addComponent(jTextField2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addComponent(jCheckBox1)))
                        .addContainerGap())))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(13, 13, 13)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File[] selectedFiles = null;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.setMultiSelectionEnabled(true);
        jf.showOpenDialog(this);
        selectedFiles = jf.getSelectedFiles();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        File dir = new File(jTextField2.getText());

        if (!dir.mkdirs()) {
            JOptionPane.showMessageDialog(rootPane, "Impossivel criar diretorio " + dir.getAbsolutePath());
            return;
        }

        jProgressBar1.setValue(10);

        if (!setFileConfig()) {
            return;
        }
        jProgressBar1.setValue(20);

        DefaultCaret caret = (DefaultCaret) jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        new Thread(new Runnable() {
            @Override
            public void run() {

                try {

                    int cont = 0;
                    Process exec = Runtime.getRuntime().exec("jhipster", new String[]{""}, dir);

                    Scanner sc = new Scanner(exec.getInputStream());

                    while (sc.hasNextLine()) {
                        String next = sc.nextLine();

                        jTextArea1.append(next + "\n");

                        if (cont++ > 1000) {
                            jTextArea1.setText("");
                            cont = 0;
                        }

                    }

                    jProgressBar1.setValue(50);

                    ///imagns
                    if (selectedFiles != null) {
                        for (File file : selectedFiles) {

                            if (file.getName().endsWith(".ico")) {

                                Files.copy(
                                        file.toPath(),
                                        new File(dir.getAbsolutePath() + "/src/main/webapp/favicon.ico").toPath(),
                                        StandardCopyOption.REPLACE_EXISTING);

                                jTextArea1.append("armazenando icone..\n");

                            } else if (file.getName().contains("logo")) {

                                jTextArea1.append("armazenando logo..\n");

                                Files.copy(
                                        file.toPath(),
                                        new File(dir.getAbsolutePath() + "/src/main/webapp/content/images/logo-jhipster.png").toPath(),
                                        StandardCopyOption.REPLACE_EXISTING);

                            } else if (file.getName().contains("2")) {
                                Files.copy(
                                        file.toPath(),
                                        new File(dir.getAbsolutePath() + "/src/main/webapp/content/images/hipster2x.png").toPath(),
                                        StandardCopyOption.REPLACE_EXISTING);
                                jTextArea1.append("armazenando imagem1..\n");
                            } else {
                                Files.copy(
                                        file.toPath(),
                                        new File(dir.getAbsolutePath() + "/src/main/webapp/content/images/hipster.png").toPath(),
                                        StandardCopyOption.REPLACE_EXISTING);
                                jTextArea1.append("armazenando imagem2..\n");
                            }

                        }
                    }

                    jProgressBar1.setValue(55);

                    ///entidades
                    if (jdl != null) {
                        exec = Runtime.getRuntime().exec(new String[]{"jhipster", "import-jdl", jdl, "--force"}, new String[]{""}, dir);

                        sc = new Scanner(exec.getInputStream());

                        while (sc.hasNextLine()) {
                            String next = sc.nextLine();

                            jTextArea1.append(next + "\n");

                            if (cont++ > 1000) {
                                jTextArea1.setText("");
                                cont = 0;
                            }

                        }

                        sc = new Scanner(exec.getErrorStream());

                        while (sc.hasNextLine()) {
                            String next = sc.nextLine();

                            jTextArea1.append("ATENCAO: " + next + "\n");

                            if (cont++ > 1000) {
                                jTextArea1.setText("");
                                cont = 0;
                            }

                        }
                    }
                    jProgressBar1.setValue(60);

                    ////pace
                    ///yo jhipster-pace
                    exec = Runtime.getRuntime().exec(new String[]{"yo", "jhipster-pace", "--force"}, new String[]{""}, dir);

                    sc = new Scanner(exec.getInputStream());
                    BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(exec.getOutputStream()));
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    while (sc.hasNextLine()) {
                        String next = sc.nextLine();

                        if (cont++ > 1000) {
                            jTextArea1.setText("");
                            cont = 0;
                        }

                        jTextArea1.append(next + "\n");

                    }

                    jProgressBar1.setValue(80);
                    //yo jhipster-angular-datatables

                    ///banner
                    exec = Runtime.getRuntime().exec(new String[]{"yo", "jhipster-banner", "--force"}, new String[]{""}, dir);

                    sc = new Scanner(exec.getInputStream());

                    sc = new Scanner(exec.getInputStream());
                    bufferedWriter = new BufferedWriter(new OutputStreamWriter(exec.getOutputStream()));
                    bufferedWriter.append(jTextField1.getText());
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.newLine();
                    bufferedWriter.flush();
                    bufferedWriter.append("n");
                    bufferedWriter.newLine();
                    bufferedWriter.flush();

                    while (sc.hasNextLine()) {
                        String next = sc.nextLine();

                        if (next.contains("banner message you wish to convert to ASCII")) {
                            bufferedWriter.newLine();
                            bufferedWriter.flush();
                            next += "  " + jTextField1.getText();
                        }

                        if (next.contains("like to use")) {
                            bufferedWriter.newLine();
                            bufferedWriter.flush();
                            next += " ENTER ";
                        }
                        if (next.contains("append")) {
                            bufferedWriter.append("n");
                            bufferedWriter.newLine();
                            bufferedWriter.flush();
                            next += " n ENTER ";
                        }

                        if (cont++ > 1000) {
                            jTextArea1.setText("");
                            cont = 0;
                        }

                        jTextArea1.append(next + "\n");

                    }

                    jProgressBar1.setValue(90);

                    ///material & navbar
                    String addGlobal = ".dropdown-menu {\\n"
                            + "    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);\\n"
                            + "    border-radius: 0px;\\n"
                            + "}\\n"
                            + "\\n"
                            + ".modal-content {\\n"
                            + "    border-radius: 0px;\\n"
                            + "    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\\n"
                            + "}\\n"
                            + "\\n"
                            + ".container-fluid {\\n"
                            + "    padding-top: 55px;\\n"
                            + "}\\n\\n";

//                    Runtime.getRuntime().exec(new String[]{"echo", addGlobal,
//                        ">>" , dir.getAbsolutePath()  +  "src/main/webapp/content/scss/global"}).waitFor();
                    Runtime.getRuntime().exec(new String[]{"sed", "-i", "'1s/^/" + addGlobal + "/'",
                        dir.getAbsolutePath() + "src/main/webapp/content/scss/global.scss"}).waitFor();

                    String addNav = ".navbar-fixed-top {\\n"
                            + "    position: fixed;\\n"
                            + "    right: 0;\\n"
                            + "    left: 0;\\n"
                            + "    z-index: 1030;\\n"
                            + "    top: 0;\\n"
                            + "}\\n"
                            + "\\n"
                            + ".jh-navbar {\\n"
                            + "    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 1px 2px 0 rgba(0, 0, 0, 0.19);\\n"
                            + "}\\n\\n";

                    Runtime.getRuntime().exec(new String[]{"sed", "-i", "'1s/^/" + addNav + "/'",
                        dir.getAbsolutePath() + "src/main/webapp/app/layouts/navbar/navbar.scss"}).waitFor();

//                    String replaceInNavHtml = " navbar-fixed-top\">";
                    Runtime.getRuntime().exec(new String[]{"sed", "-i", "'1s/\">/ navbar-fixed-top\">/'",
                        dir.getAbsolutePath() + "src/main/webapp/app/layouts/navbar/navbar.html"}).waitFor();

//                    "content: 'LOADING';";
//                    String labelLoad = "content: 'CARREGANDO SISTEMA...';";
                    Runtime.getRuntime().exec(new String[]{"sed", "-i",
                        "'s/LOADING/CARREGANDO SISTEMA.../'",
                        dir.getAbsolutePath() + "src/main/webapp/index.html"}).waitFor();

                    jProgressBar1.setValue(100);

                    JOptionPane.showMessageDialog(rootPane, "O app foi criado com sucesso!");

                    Runtime.getRuntime().exec(new String[]{"gnome-terminal",
                        "--working-directory=" + dir.getAbsolutePath(), "-x", "./mvnw"}).waitFor();

                    Runtime.getRuntime().exec(new String[]{"gnome-terminal",
                        "--working-directory=" + dir.getAbsolutePath(), "-x", "sudo", "yarn", "start"}).waitFor();
                    Runtime.getRuntime().exec(new String[]{"gnome-terminal",
                        "--working-directory=" + dir.getAbsolutePath(), "-x", "yarn", "install"}).waitFor();

                    Runtime.getRuntime().exec(new String[]{"git", "init"}).waitFor();
                    Runtime.getRuntime().exec(new String[]{"git", "add", "*"}).waitFor();
                    Runtime.getRuntime().exec(new String[]{"git", "commit", "-m", "\"commit inicial\""}).waitFor();
                    if (jCheckBox1.isSelected()) {
                        System.exit(0);
                    }

                } catch (IOException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }).start();


    }//GEN-LAST:event_jButton2ActionPerformed


    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

        jTextField2.setText("/home/mfernandes/" + jTextField1.getText().toLowerCase() + "/");

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jTextField2.setText("/home/mfernandes/" + jTextField1.getText().toLowerCase() + "/");
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jTextField2.setText("/home/mfernandes/" + jTextField1.getText().toLowerCase() + "/");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.setMultiSelectionEnabled(false);
        jf.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith("jh") | f.isDirectory();
            }

            @Override
            public String getDescription() {
                return "arquivos JDL";
            }
        });
        jf.showOpenDialog(this);

        jdl = jf.getSelectedFile().getAbsolutePath();

    }//GEN-LAST:event_jButton3ActionPerformed

    String jdl = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    boolean setFileConfig() {

        String base = "{\n"
                + "  \"generator-jhipster\": {\n"
                + "    \"promptValues\": {\n"
                + "      \"packageName\": \"com.mikeias." + jTextField1.getText().toLowerCase() + "\",\n"
                + "      \"nativeLanguage\": \"pt-br\"\n"
                + "    },\n"
                + "    \"jhipsterVersion\": \"4.8.2\",\n"
                + "    \"baseName\": \"" + jTextField1.getText() + "\",\n"
                + "    \"packageName\": \"com.mikeias." + jTextField1.getText().toLowerCase() + "\",\n"
                + "    \"packageFolder\": \"com/mikeias/" + jTextField1.getText().toLowerCase() + "\",\n"
                + "    \"serverPort\": \"8080\",\n"
                + "    \"authenticationType\": \"oauth2\",\n"
                + "    \"hibernateCache\": \"ehcache\",\n"
                + "    \"clusteredHttpSession\": false,\n"
                + "    \"websocket\": \"spring-websocket\",\n"
                + "    \"databaseType\": \"sql\",\n"
                + "    \"devDatabaseType\": \"h2Disk\",\n"
                + "    \"prodDatabaseType\": \"postgresql\",\n"
                + "    \"searchEngine\": false,\n"
                + "    \"messageBroker\": false,\n"
                + "    \"serviceDiscoveryType\": false,\n"
                + "    \"buildTool\": \"maven\",\n"
                + "    \"enableSocialSignIn\": false,\n"
                + "    \"enableSwaggerCodegen\": false,\n"
                + "    \"clientFramework\": \"angularX\",\n"
                + "    \"useSass\": true,\n"
                + "    \"clientPackageManager\": \"yarn\",\n"
                + "    \"applicationType\": \"monolith\",\n"
                + "    \"testFrameworks\": [],\n"
                + "    \"jhiPrefix\": \"jhi\",\n"
                + "    \"otherModules\": [\n"
                + "      {\n"
                + "        \"name\": \"generator-jhipster-pace\",\n"
                + "        \"version\": \"0.1.3\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"name\": \"generator-jhipster-banner\",\n"
                + "        \"version\": \"0.1.0\"\n"
                + "      }\n"
                + "    ],\n"
                + "    \"enableTranslation\": true,\n"
                + "    \"nativeLanguage\": \"pt-br\",\n"
                + "    \"languages\": [\n"
                + "      \"pt-br\",\n"
                + "      \"en\"\n"
                + "    ]\n"
                + "  }\n"
                + "}";

        try {
            FileWriter fw = new FileWriter(jTextField2.getText() + ".yo-rc.json");

            fw.write(base);
            fw.close();
            return true;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Impossivel escrever arquivo "
                    + jTextField2.getText() + ".yo-rc.json" + "\n error: " + ex);
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
